repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.0.1
    hooks:
      - id: check-yaml
      - id: end-of-file-fixer
      - id: trailing-whitespace
  - repo: https://github.com/radix-ai/auto-smart-commit
    rev: v1.0.2
    hooks:
      - id: auto-smart-commit
  - repo: https://github.com/psf/black
    rev: 21.12b0
    hooks:
      - id: black
        args: ["--check", "--diff"]
  - repo: https://github.com/pycqa/isort
    rev: 5.10.1
    hooks:
      - id: isort
        args: ["--profile=black"]
  - repo: https://github.com/pycqa/pydocstyle
    rev: 6.1.1
    hooks:
      - id: pydocstyle
        args: ["--convention=google"]
  - repo: https://github.com/pycqa/bandit
    rev: 1.7.1
    hooks:
      - id: bandit
        exclude: ^tests/
  - repo: https://github.com/pycqa/flake8
    rev: 3.9.2
    hooks:
      - id: flake8
        args: ["--max-line-length=119", "--extend-ignore=E203,W503"]
  - repo: https://github.com/pycqa/pylint
    rev: v2.12.2
    hooks:
      - id: pylint
        exclude: ^tests/
        args: ["--max-line-length=119"]
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.910
    hooks:
      - id: mypy
