name: push
on: push
defaults:
  run:
    shell: bash -l {0}
jobs:
  linting-tests:
    name: Linting tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: conda-incubator/setup-miniconda@v2
        with:
          activate-environment: template
          environment-file: conda.yml
          miniforge-version: latest
      - uses: google-github-actions/auth@v0.4.0
        with:
          credentials_json: ${{ secrets.gcp_credentials }}
      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v0.2.1
      - name: Install poetry
        run: |
          curl -sSL https://install.python-poetry.org | python - -p
          poetry plugin add keyrings.google-artifactregistry-auth
      - name: Install dependencies
        run: |
          poetry install
      - name: Code style & linting tests
        run: |
          pytest --black --isort --pydocstyle --bandit --flake8 --pylint --mypy --lint-only
  unit-tests:
    name: Unit tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: conda-incubator/setup-miniconda@v2
        with:
          activate-environment: template
          environment-file: conda.yml
          miniforge-version: latest
      - uses: google-github-actions/auth@v0.4.0
        with:
          credentials_json: ${{ secrets.gcp_credentials }}
      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v0.2.1
      - name: Install poetry
        run: |
          curl -sSL https://install.python-poetry.org | python - -p
          poetry plugin add keyrings.google-artifactregistry-auth
      - name: Install dependencies
        run: |
          poetry install
      - name: Unit tests
        run: |
          pytest -n auto --cov-fail-under 100 --cov-config pyproject.toml --cov=template -m unit_test
  functional-tests:
    name: Functional tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: conda-incubator/setup-miniconda@v2
        with:
          activate-environment: template
          environment-file: conda.yml
          miniforge-version: latest
      - uses: google-github-actions/auth@v0.4.0
        with:
          credentials_json: ${{ secrets.gcp_credentials }}
      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v0.2.1
      - name: Install poetry
        run: |
          curl -sSL https://install.python-poetry.org | python - -p
          poetry plugin add keyrings.google-artifactregistry-auth
      - name: Install dependencies
        run: |
          poetry install
      - name: Functional tests
        run: |
          pytest -n auto --cov-fail-under 100 --cov-config pyproject.toml --cov=template -m functional_test
